# Generated by Django 4.0.2 on 2022-06-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsman', '0002_news_author'),
        ('Newsman', '0003_alter_news_author'),
    ]

    operations = [
    ]
