# Generated by Django 4.0.2 on 2022-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsman', '0004_merge_0002_news_author_0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать автора'),
        ),
    ]
