# Generated by Django 4.0.2 on 2022-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsman', '0005_news_author_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_visible',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отображать автора'),
        ),
    ]
